# Generated by Django 2.1.3 on 2018-12-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_imageuploadfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadfield',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
