# Generated by Django 2.1.5 on 2019-01-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_commentfield_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenFiled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
            ],
        ),
    ]
